// This file is auto-generated by scripts/generate-model-exports.mjs
export type { CollectionResponseDataExtDefinition, CreateCustomFieldDefinitionRequest, DataExtDefinition, DeleteCustomFieldDefinitionRequest, UpdateCustomFieldDefinitionRequest } from '../../generated/index.js';
