// This file is auto-generated by scripts/generate-model-exports.mjs
export type { BasePageResponseDeposit, CashBackInfo, CashBackInfoRequest, CreateDepositLineRequest, CreateDepositRequest, Deposit, DepositLine, DepositManualLineRequest, DepositPaymentLineRequest, UpdateDepositLineRequest, UpdateDepositRequest } from '../../generated';
