// This file is auto-generated by scripts/generate-model-exports.mjs
export type { BasePageResponseInventorySite, CreateInventorySiteRequest, InventorySite, UpdateInventorySiteRequest } from '../../generated';
