// This file is auto-generated by scripts/generate-model-exports.mjs
export type { CreateItemOtherChargeRequest, ItemOtherCharge, ItemOtherChargeSalesAndPurchaseDetailsRequest, ItemOtherChargeSalesOrPurchaseDetailsRequest, UpdateItemOtherChargeRequest } from '../../generated';
