// This file is auto-generated by scripts/generate-model-exports.mjs
export type { CreateItemNonInventoryRequest, ItemNonInventory, ItemNonInventorySalesAndPurchaseDetailsRequest, ItemNonInventorySalesOrPurchaseDetailsRequest, UpdateItemNonInventoryRequest } from '../../generated/index.js';
