// This file is auto-generated by scripts/generate-model-exports.mjs
export type { BasePageResponseItemFixedAsset, CreateItemFixedAssetRequest, ItemFixedAsset, UpdateItemFixedAssetRequest } from '../../generated';
