// This file is auto-generated by scripts/generate-model-exports.mjs
export type { BasePageResponseInventoryItem, CreateInventoryItemRequest, InventoryItem, UpdateInventoryItemRequest } from '../../generated';
