// This file is auto-generated by scripts/generate-model-exports.mjs
export type { BasePageResponseServiceItem, CreateSalesAndPurchaseRequest, CreateSalesOrPurchaseRequest, CreateServiceItemRequest, ServiceItem, UpdateSalesAndPurchaseRequest, UpdateSalesOrPurchaseRequest, UpdateServiceItemRequest } from '../../generated';
