// This file is auto-generated by scripts/generate-model-exports.mjs
export type { BasePageResponseItemInventoryAssembly, CreateItemInventoryAssemblyLineRequest, CreateItemInventoryAssemblyRequest, ItemInventoryAssembly, UpdateItemInventoryAssemblyLineRequest, UpdateItemInventoryAssemblyRequest } from '../../generated';
