// This file is auto-generated by scripts/generate-model-exports.mjs
export type { CreateSalesOrderLineGroupRequest, CreateSalesOrderLineRequest, CreateSalesOrderRequest, SalesOrder, SalesOrderLine, SalesOrderLineGroup, ShippingDetailsLine, UpdateSalesOrderLineGroupRequest, UpdateSalesOrderLineRequest, UpdateSalesOrderRequest } from '../../generated';
