// This file is auto-generated by scripts/generate-model-exports.mjs
export type { BasePageResponseSalesReceipt, CreateSalesReceiptLineGroupRequest, CreateSalesReceiptLineRequest, CreateSalesReceiptRequest, SalesReceipt, SalesReceiptLine, SalesReceiptLineGroup, UpdateSalesReceiptLineGroupRequest, UpdateSalesReceiptLineRequest, UpdateSalesReceiptRequest } from '../../generated';
