// This file is auto-generated by scripts/generate-model-exports.mjs
export type { BasePageResponseSalesOrder, CreateSalesOrderLineRequest, CreateSalesOrderRequest, SalesOrder, SalesOrderLine, UpdateSalesOrderLineRequest, UpdateSalesOrderRequest } from '../../generated';
